######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 31 10:35:10 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += server.h
SOURCES += main.cpp
