######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 31 10:38:08 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
SOURCES += main.cpp
