######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 19 15:52:38 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
