######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 12 16:47:00 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mylineedit.h widget.h
FORMS += widget.ui
SOURCES += main.cpp mylineedit.cpp widget.cpp
